title: Random Stuff
description: A blog about technology, travels, cooking, software development, and more
author: Miguel Moreno
baseurl: "/random-stuff"
url: "https://miguelnazmor.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-multiple-languages-plugin

# Sass settings
sass:
  style: compressed
  sourcemap: never

# Language settings
languages: ["en", "es"]
default_lang: "en"
exclude_from_localizations: ["javascript", "images", "css", "scripts"]

# Categories
categories: [technology, travels, cooking, software]

# Default front matter
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Miguel Moreno"
